name: Java CI/CD Workflow

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: 使用 Maven 构建项目并运行 PMD
      - name: Build with Maven and run PMD
        run: mvn clean install pmd:pmd

      # Step 4: 上传 PMD 报告为 Artifact
      - name: Upload PMD Report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: target/site/pmd.html

      # Step 5: 登录到 Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 6: 构建 Docker 镜像，确保路径正确
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/texteditor3:latest .

      # Step 7: 检查 Docker 镜像是否成功构建
      - name: Check Docker build success
        run: docker inspect ${{ secrets.DOCKER_USERNAME }}/texteditor3:latest

      # Step 8: 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/texteditor3:latest

      # Step 9: 清理 Docker 镜像
      - name: Clean up Docker image
        run: docker rmi ${{ secrets.DOCKER_USERNAME }}/texteditor3:latest
